### ISSUE TITLE
Неверный подсчет и отображение баланса при использование класса pay

### ISSUE THREAD

**Issue by KatyaQA91** [ElenaBairamova/javateamwork#10]
# Описание

По условию требований, в результате успешного вызова этого метода, баланс должен уменьшиться на сумму покупки. Если же операция может привести к некорректному состоянию счёта (например, баланс может уйти в минус), то операция должна завершиться вернув false и ничего не поменяв на счёте. При тестировании данного метода Баланс ушел в минус. Тест не прошел

# Локализация дефекта

https://github.com/ElenaBairamova/javateamwork/blob/543312b245dc00acb09022aeea875f9ad05a6489/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/ElenaBairamova/javateamwork/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) В IDEA
2. Открыть вкладку [SavingAccountTest.java](https://github.com/ElenaBairamova/javateamwork/blob/main/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java)
3. Запустить тест  balanceMinBalanc
- _Ожидаемый результат:_ ответ должен быть 2000
- _Фактический результат:_ ответ - 1000

# Скриншот

![image](https://github.com/ElenaBairamova/javateamwork/assets/129439080/25b368a8-cc94-4711-a519-964c2b2f0d08)

# Окружение

 - Операционная система Windows 10 Pro
- IDE : Intellij IDEA 2023.1
- Java : Open JDK 11

**Comment by ElenaBairamova** [comment]
Исправлено, тест проходит, в тесте была ошибка - ожидаемый результат - 1_000, так как вернуть должен начальный баланс.
