### ISSUE TITLE
При расчёта процентов на остаток счёта при условии, что счёт не будет меняться год, расчёт процентов не производится

### ISSUE THREAD

**Issue by KatyaQA91** [ElenaBairamova/javateamwork#11]
# Описание
В требовании класса public int yearChange() сказано, что  Операция расчёта процентов на остаток счёта производиться при условии, что счёт не будет меняться год. При тестировании  тест выдает изначальный баланс, не производя расчет процентов от суммы.

# Локализация дефекта
https://github.com/ElenaBairamova/javateamwork/blob/543312b245dc00acb09022aeea875f9ad05a6489/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/ElenaBairamova/javateamwork/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) В IDEA
2. Открыть вкладку [SavingAccountTest.java](https://github.com/ElenaBairamova/javateamwork/blob/main/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java)
3. Запустить тест checkingTheCalculationOfInterestOnTheBalanceOfTheAccount
- _Ожидаемый результат:_ ответ должен быть 50
- _Фактический результат:_ ответ 1000

# Скриншот

![image](https://github.com/ElenaBairamova/javateamwork/assets/129439080/9eb45894-ab0e-4336-af2f-43e686426e04)

# Окружение
- Операционная система Windows 10 Pro
- IDE: Intellij IDEA 2023.1
- Java: Open JDK 11

**Comment by ElenaBairamova** [comment]
Исправлено, в тесте выводится getBalance, а должно account.yearChange.
