### ISSUE TITLE
При совершении покупки сумма остатка равна минимальному значению, но вместо  true возвращается false

### ISSUE THREAD

**Issue by KatyaQA91** [ElenaBairamova/javateamwork#12]
# Описание
В требовании сказано, что в случаи совершении покупки и остатка на балансе суммы, равной минимальному значению, метод pay возвращает  true. При тестировании метод вернул false. Тест не прошел

https://github.com/ElenaBairamova/javateamwork/blob/543312b245dc00acb09022aeea875f9ad05a6489/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/ElenaBairamova/javateamwork/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Открыть вкладку [SavingAccountTest.java](https://github.com/ElenaBairamova/javateamwork/blob/main/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java)
3. Запустить тест checkingTheCalculationOfMinBalanceWhenBuying
- _Ожидаемый результат:_ консоль возвращает true, и баланс на счете должен остаться 1000.
- _Фактический результат:_ консоль возвращает false, баланс становится  1000.

# Скриншот
![image](https://github.com/ElenaBairamova/javateamwork/assets/129439080/f8e4d4ec-b5ef-46a2-b4ac-4fa084ef8829)

# Окружение
Операционная система Windows 10 Pro
IDE: Intellij IDEA 2023.1
Java: Open JDK 11

**Comment by ElenaBairamova** [comment]
Исправлено, тест проходит
