### ISSUE TITLE
Не отображается исключение IllegalArgumentException, если изначально баланс больше максимального

### ISSUE THREAD

**Issue by KatyaQA91** [ElenaBairamova/javateamwork#9]
# Описание
 В первичных требованиях указано, что если параметры некорректны : начальный баланс не может быть больше максимального то должно отобразиться исключения, вида IllegalArgumentException.  Тест не проходит, т.к. условия не реализовывают требования

# Локализация дефекта

https://github.com/ElenaBairamova/javateamwork/blob/543312b245dc00acb09022aeea875f9ad05a6489/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Открыть вкладку [SavingAccount.java](https://github.com/ElenaBairamova/javateamwork/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java)
3. Запустить тест icheckingTheBalanceForEqualityToTheMinBalance
4. Произвести проверку вывода исключения вида IllegalArgumentException при создании объекта, если начальный баланс больше максимального
 - _Ожидаемый результат_: выкидывается исключение и тест проходит
 - _Фактический результат_: исключение не выкидывается и тест не проходит

# Скриншот

![image](https://github.com/ElenaBairamova/javateamwork/assets/129439080/b8f377b1-4c21-43d7-b324-d727b8596aa0)

# Окружение

- Операционная система Windows 10 Pro
- IDE : Intellij IDEA 2023.1
- Java : Open JDK 11

**Comment by ElenaBairamova** [comment]
Исправлено, тест проходит.
